import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { MenuList, MenuListItem, Separator, styleReset } from "react95";
import { createGlobalStyle, ThemeProvider } from "styled-components";
import AppBar from "../components/Navbar";

/* Pick a theme of your choice */
import original from "react95/dist/themes/original";

/* Original Windows95 font (optional) */
import ms_sans_serif from "react95/dist/fonts/ms_sans_serif.woff2";
import ms_sans_serif_bold from "react95/dist/fonts/ms_sans_serif_bold.woff2";

const inter = Inter({ subsets: ["latin"] });
// src: url('${ms_sans_serif}') format('woff2');
// src: url('${ms_sans_serif_bold}') format('woff2');

const GlobalStyles = createGlobalStyle`
${styleReset}
@font-face {
  font-family: 'ms_sans_serif';
    font-weight: 400;
    font-style: normal
  }
  @font-face {
    font-family: 'ms_sans_serif';
    font-weight: bold;
    font-style: normal
  }
  body, input, select, textarea {
    font-family: 'ms_sans_serif';
  }
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyles />
      <ThemeProvider theme={original}>
        <main className={styles.main}>
          <h1 className="text-red-500 text-3xl">It's me</h1>
          <MenuList>
            <MenuListItem>🎤 Sing</MenuListItem>
            <MenuListItem>💃🏻 Dance</MenuListItem>
            <Separator />
            <MenuListItem disabled>😴 Sleep</MenuListItem>
          </MenuList>
          <AppBar />
        </main>
      </ThemeProvider>
    </>
  );
}
